version: '3'

services:
  aira-go:
    build: .
    container_name: aira-go
    restart: always
    environment:
      TIME_SPAN: 3600 # second
      TZ: Asia/Shanghai
      OUTPUT: stdout
      CYCLO_BAR: "1,5,20"
    volumes:
      - codePath:/app # {your code path}:/app
